import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          My name is <a href="https://nextjs.org">Hanjiweon</a>
        </h1>

        <p className={styles.description}>
          About me!{' '}
          
        </p>

        <div className={styles.grid}>
          <a href="https://nextjs.org/docs" className={styles.card}>
            <h2>My hobby &rarr;</h2>
            <p>Playing games, hang out with friends, watching youtube and Netflix.</p>
          </a>

          <a href="https://nextjs.org/learn" className={styles.card}>
            <h2>What I like &rarr;</h2>
            <p>Friends, family, game, car, electronic product, delicious food</p>
          </a>

          <a
            href="https://github.com/vercel/next.js/tree/canary/examples"
            className={styles.card}
          >
            <h2>What I don't like &rarr;</h2>
            <p>Homework, test, studying what I don't have interests.</p>
          </a>

          <a
            href="https://vercel.com/new?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            className={styles.card}
          >
            <h2>My goal &rarr;</h2>
            <p>
              Living happy and healthy with my family and friends.
            </p>
          </a>
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}
